const express = require('express');
const error = require('../middleware/error');
const auth = require('../app/controllers/auth');
const users = require('../app/controllers/users');
const carBrands = require('../app/controllers/carBrand');
const batteryCompany = require('../app/controllers/batteryCompany');
const battery = require('../app/controllers/battery');
const batteryStock = require('../app/controllers/batteryStock');
const tyreStock = require('../app/controllers/tyreStock');
const oilStock = require('../app/controllers/oilStock');
const vehicles = require('../app/controllers/vehicles');
const inquiry = require('../app/controllers/inquiry');
const sec = require('../middleware/sec');
const image = require('../app/controllers/image');
const package = require('../app/controllers/washPackages');
const notif = require('../app/controllers/notification');
const job = require('../app/controllers/jobAssign');
const otp = require('../app/controllers/otp');
const live = require('../app/controllers/live');
const path = require("path");
const jobAssign = require('../app/controllers/jobAssign');
const company = require('../app/controllers/company');
const tyre = require('../app/controllers/tyre');
const oil = require('../app/controllers/oil');
const location = require('../app/controllers/locations');
const contact = require('../app/controllers/mail');
module.exports = function (app) {
	app.use(express.json());
	app.use(function (req, res, next) {
		res.header('Access-Control-Allow-Origin', '*');
		res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,PATCH,OPTIONS');
		res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization,key ,Accept-Encoding, Accept-Language ,Origin');
		next();
	});
	app.use("/images", express.static(path.join("public/images")));

	app.use('/api/auth', auth);
	app.use('/api/users', users);
	app.use('/api/vehicle', vehicles);
	app.use('/api/carBrand', carBrands);
	app.use('/api/batteryCompany', batteryCompany);
	app.use('/api/battery', battery);
	app.use('/api/batteryStock', batteryStock);
	app.use('/api/image', image);
	app.use('/api/inquiry', inquiry);
	app.use('/api/package', package);
	app.use('/api/job', jobAssign);
	app.use('/api/notif', notif);
	app.use('/api/live', live);
	app.use('/api/otp', otp);
	app.use('/api/company', company);
	app.use('/api/tyre', tyre);
	app.use('/api/tyreStock', tyreStock);
	app.use('/api/oilStock', oilStock);
	app.use('/api/oil', oil);
	app.use('/api/location', location);
	app.use('/api/contact', contact);
	app.use(error);
}